### ISSUE TITLE
Creating a new note based on previous note

### ISSUE THREAD

**Issue by jjjchens235** [marph91/joppy#12]
Hi, thank you for creating this Python wrapper.

I have a certain use case and was hoping you could advise if this is doable or not.

From a high level, I want to create a new note each from a template note (just a regular note that I'm going to use as a template).

From looking at `api.py` I was planning to use `get_note()` to obtain the template note's body, and then pass that into `add_note()`. Is this the right idea? Thank you in advance.

**Comment by marph91** [comment]
Hi @jjjchens235, thanks for trying joppy :) I think it's doable. You had the correct idea.

I tried to write some text, but I think it's easier understandable as code snippet:

```python3
##### boilerplate code

import time
from joppy.api import Api

api = Api(token="YOUR_TOKEN")

api.add_notebook(title="Notebook for template note")
api.add_note(title="Template note", body="Template note content")

# Joplin needs some time to register the new note at its search engine.
# Use a hard sleep for convenience.
time.sleep(15)

#####

# Basically almost all API interactions need an ID.
# So the first step would be to get the ID of the template note.
# You could do that by either using the `search()` method
# (it would be good if your note would have a unique title to get only a single search result)
# or get the ID from the developer tools inside joplin and hardcode it.
search_result = api.search(query="Template note")
assert len(search_result["items"]) == 1
template_note_id = search_result["items"][0]["id"]

# Now you can use the ID to get the note body of the template note.
template_note = api.get_note(id_=template_note_id, fields="id,title,body")

# Modify the template here.
new_note = {
    "title": template_note["title"] + " some string",
    "body": template_note["title"] + "\nanother string",
}

# Create the new note in joplin.
api.add_note(**new_note)
```

**Comment by jjjchens235** [comment]
That's exactly what I was looking for.

Looking forward to trying this out and thank you for your guidance.

**Comment by marph91** [comment]
Fine. Feel free to reopen this issue if you have a follow up question.
