### ISSUE TITLE
get_resource: does not work for filedata

### ISSUE THREAD

**Issue by mheden** [marph91/joppy#13]
It seems like `get_resource` with the argument `get_file=True` will fail since the Joplin API is sending a binary blob in this case and not json data.

Excerpt:
```
Traceback (most recent call last):
  File "C:\devel\joplin\.venv\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
...
    pprint(api.get_resource(id_, get_file=True))
  File "C:\devel\joplin\.venv\lib\site-packages\joppy\api.py", line 265, in get_resource
    response: JoplinItem = self.get(f"/resources/{id_}/file", query=query).json()
  File "C:\devel\joplin\.venv\lib\site-packages\requests\models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] �PNG
→
IHDR☻g♠��D� IDATx���l[������N+�
...
```

version info:
joppy:              0.0.6
Joplin 2.7.15 (prod, win32)
Sync Version: 3
Profile Version: 41
Revision: 8352e23

**Comment by mheden** [comment]
Maybe add a `data` attribute to `JoplinItem` and do something like this:

```py
    def get_resource(
        self, id_: str, get_file: bool = False, **query: JoplinTypes
    ) -> JoplinItem:
        """Get the resource with the given ID."""
        if get_file:
            response: JoplinItem = {'data': self.get(f"/resources/{id_}/file").content}
        else:
            response: JoplinItem = self.get(f"/resources/{id_}", query=query).json()
        return response
```

**Comment by marph91** [comment]
Hi, thanks for the bug report!

I wasn't aware of this flag. It seems to be not documented at https://joplinapp.org/api/references/rest_api/ and I can't find any other reference. Do you have maybe any reference of this flag?

However, it seems to be available in the API and joppy shouldn't throw an exception. Your suggestion looks reasonable. I will have time to take a closer look tomorrow.

**Comment by mheden** [comment]
Thanks!

Maybe it's a bit weird to force something into JSON when there is just a binary blob (and also since `query` doesn't work with the `/file` endpoint so another suggestion is that the API function is split into two instead:

```

**Comment by mheden** [comment]
It's probably better if you do it then :-)
