### ISSUE TITLE
When exporting notes to pdf, the image resource fails to load.

### ISSUE THREAD

**Issue by cestbonsuliu** [marph91/joppy#19]
# Problem Description

I encountered the following error when running note_export.py to export notes to PDF

```
WARNING:pypandoc:This document format requires a nonempty <title> element.
  Defaulting to '-' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
ERROR: Failed to load image at 'file:///D:/PycharmProjects/pythonProject/:/8cbb74f887a64d579b65
9d164f1bdebd': OSError: Bad URL: /D|/PycharmProjects/pythonProject/|/8cbb74f887a64d579b659d164f
1bdebd
ERROR: Failed to load image at 'file:///D:/PycharmProjects/pythonProject/:/d13e4a8f680740299aaf
161958dac938': OSError: Bad URL: /D|/PycharmProjects/pythonProject/|/d13e4a8f680740299aaf161958
dac938
ERROR: Failed to load image at 'file:///D:/PycharmProjects/pythonProject/:/44eac417e2c74aacafa6
a6d8973f77e4': OSError: Bad URL: /D|/PycharmProjects/pythonProject/|/44eac417e2c74aacafa6a6d897
3f77e4

```

![image](https://user-images.githubusercontent.com/34851775/233046656-e4da30b6-52c8-4824-9c60-dc7b2c0dd5c5.png)

The code block does not render well and the image fails to load. How can I solve this problem?

**Comment by cestbonsuliu** [comment]
Thank you very much for the quick improvement！ I will try to wait for my work to finish

**Comment by cestbonsuliu** [comment]
hey bro, sorry for the delay of a few days. After my testing I found that there are still problems with.

Execute the following code:

```
note = api.get_note(id_=candidate.id, fields="body")
```
Got the body of the note:

"
应用布局”视图中，可以看到应用程序添加这些拆分器的位置。

!\[d04840c9e13f308719809a495b4d536e.png\](:/22ada25077f944c6ae999daf40bd8988)

```
/* remove white border (~5px, right) from columns with one panel */
.rli-root > .resizableLayoutItem > div {
  width: 100% !important;
}
/* remove white border (~5px, right, below) from columns with two or more panels */
.rli-root > .resizableLayoutItem > .resizableLayoutItem > div {
  height: 100% !important;
  width: 100% !important;
}
/* remove small border (1px, below) plugin iframes */
div.resizableLayoutItem iframe {
  border-bottom: none !important;
}
```


会导致插件出现问题，如下

!\[fa0e980914c7ef6e4be4dac3acec9b6c.png\](:/55dfd6b9efe14dafb2a619950de86d18)

"
---

The problems in the final obtained pdf:

- Image cannot be displayed

![image](https://user-images.githubusercontent.com/34851775/233841072-99a04b86-e211-4209-acce-300ff14b433e.png)

![image](https://user-images.githubusercontent.com/34851775/233841092-d009a03a-06ab-4a51-9d0e-0a711eda345a.png)

```
[WARNING] WARNING: Ignored `text-rendering: optimizeLegibility` at 15:7, unknown property.
WARNING: Expected a media type, got '(max-width: 600px)'
WARNING: Invalid media type ' (max-width: 600px) ' the whole @media rule was ignored at 18:5.
WARNING: Ignored `overflow-x: auto` at 108:7, unknown property.
WARNING: Ignored `gap: min(4vw, 1.5em)` at 145:32, unknown property.
WARNING: Ignored `overflow-x: auto` at 146:28, unknown property.
ERROR: Failed to load image at 'C:%5CUsers%5Cadmin%5CAppData%5CLocal%5CTemp%5Ctmphj9p5h13/22ada
25077f944c6ae999daf40bd8988': ValueError: Not an absolute URI: 'C:%5CUsers%5Cadmin%5CAppData%5C
Local%5CTemp%5Ctmphj9p5h13/22ada25077f944c6ae999daf40bd8988'
ERROR: Failed to load image at 'C:%5CUsers%5Cadmin%5CAppData%5CLocal%5CTemp%5Ctmphj9p5h13/55dfd
6b9efe14dafb2a619950de86d18': ValueError: Not an absolute URI: 'C:%5CUsers%5Cadmin%5CAppData%5C
Local%5CTemp%5Ctmphj9p5h13/55dfd6b9efe14dafb2a619950de86d18'

WARNING:pypandoc:WARNING: Ignored `text-rendering: optimizeLegibility` at 15:7, unknown propert
y.
WARNING: Expected a media type, got '(max-width: 600px)'
WARNING: Invalid media type ' (max-width: 600px) ' the whole @media rule was ignored at 18:5.
WARNING: Ignored `overflow-x: auto` at 108:7, unknown property.
WARNING: Ignored `gap: min(4vw, 1.5em)` at 145:32, unknown property.
WARNING: Ignored `overflow-x: auto` at 146:28, unknown property.
ERROR: Failed to load image at 'C:%5CUsers%5Cadmin%5CAppData%5CLocal%5CTemp%5Ctmphj9p5h13/22ada
25077f944c6ae999daf40bd8988': ValueError: Not an absolute URI: 'C:%5CUsers%5Cadmin%5CAppData%5C
Local%5CTemp%5Ctmphj9p5h13/22ada25077f944c6ae999daf40bd8988'
ERROR: Failed to load image at 'C:%5CUsers%5Cadmin%5CAppData%5CLocal%5CTemp%5Ctmphj9p5h13/55dfd
6b9efe14dafb2a619950de86d18': ValueError: Not an absolute URI: 'C:%5CUsers%5Cadmin%5CAppData%5C
Local%5CTemp%5Ctmphj9p5h13/55dfd6b9efe14dafb2a619950de86d18'

```



- Code blocks not highlighted

![image](https://user-images.githubusercontent.com/34851775/233841415-58dc673c-580b-4e76-af6f-c43e6274c687.png)

**Comment by marph91** [comment]
Ah, I see. On my linux machine it works, but I can reproduce in a windows VM. I can probably take a look at the issue this week.

**Comment by marph91** [comment]
@cestbonsuliu Could you test once more? It should be fixed on master (at least on my windows VM). I didn't [use the file protocol properly](https://stackoverflow.com/a/18246357/7410886).

Two remarks (not directly related to the issue):

- I'm getting the ```WARNING: Ignored `text-rendering: optimizeLegibility` at 15:7, unknown property.``` warning on windows too, but couldn't find out the issue. It's probably related to images (https://github.com/Kozea/WeasyPrint/issues/1655).
- Images are not scaled to the page width. I will look for a fix.

**Comment by cestbonsuliu** [comment]
I'm happy to report that the feature implementation was successful.I really appreciate your prompt and thorough assistance with my Github issue.
