### ISSUE TITLE
add_resource_to_note assumes it is an image

### ISSUE THREAD

**Issue by init-random** [marph91/joppy#24]
Please see here
https://github.com/marph91/joppy/blob/cc3d1f4d0c3b6fea08b8e8ed76c44eac2c512a45/joppy/api.py#L338C9-L338C9

If the resource is an image, this line is fine. 
```body_with_attachment = f"{note.body}\n![{resource.title}](:/{resource_id})"```
Otherwise, we should not include the exclamation mark, i.e. it should be
```body_with_attachment = f"{note.body}\n[{resource.title}](:/{resource_id})"```
as in the case of adding a PDF resource.

The inclusion exclamation mark for non-images makes the resource unable to render.

**Comment by marph91** [comment]
Thanks for the report! I will try to release a fix soon.
